### ISSUE TITLE
[BUG] terraform-docs isn't being installed right

### ISSUE THREAD

**Issue by sblack4** [rhythmictech/terraform-terraform-template#28]
They've been releasing a lot lately but I know v10+ were having issues with pre-commit hooks. This will take a little investigating into which version we can install (I think v9 is fine)

Here's what I have on my machine (it works fine)
```
$ terraform-docs --version                                                                                                                                                       
terraform-docs version v0.9.1 7f761d3 darwin/amd64 BuildDate: 2020-04-02T21:58:38+0000
```

And the error I'm seeing in a workflow

```
Terraform docs...........................................................Failed
- hook id: terraform_docs
- exit code: 1

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at Socket.<anonymous> (/home/runner/work/_temp/5e7bccb8-b608-405f-a9c7-1a943190224a/terraform:750:54)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
ERROR: terraform-docs is required by terraform_docs pre-commit hook but is not installed or in the system's PATH.

```

**Comment by sblack4** [comment]
found evidence of the bug causing this. something is wrong with the URL 

```
curl: (3) URL using bad/illegal format or missing URL
```

https://github.com/rhythmictech/terraform-terraform-template/pull/31/checks?check_run_id=2124313264#step:4:53

**Comment by sblack4** [comment]
Ahh, it was getting two urls
```sh
➜  terraform-terraform-template git:(fix-27-28) ✗ curl -L "$(curl -sL https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | grep -o -E "https://.+?-linux-amd64")"
curl: (3) URL using bad/illegal format or missing URL
➜  terraform-terraform-template git:(fix-27-28) ✗ curl -sL https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | grep -o -E "https://.+?-linux-amd64" 
https://github.com/terraform-docs/terraform-docs/releases/download/v0.11.2/terraform-docs-v0.11.2-linux-amd64
https://github.com/terraform-docs/terraform-docs/releases/download/v0.11.2/terraform-docs-v0.11.2-linux-amd64
```

**Comment by sblack4** [comment]
It looks like terraform-docs version `0.11.2` works in a pre-commit hook! Here's my version 

```
➜  terraform-terraform-template git:(fix-27-28) terraform-docs --version
terraform-docs version v0.11.2 darwin/amd64 BuildDate: 2021-02-23T00:11:34+0000
```
